/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Cat_MASTER_Selfie_2.glb
*/

import React from 'react'
import { useGraph, useLoader } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { TextureLoader, SRGBColorSpace } from 'three'
import { texture, uv } from 'three/tsl'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Cat_MASTER_Selfie_2.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  const catBase = useLoader(TextureLoader, '/textures/CatBase.webp')

  const catMat = React.useMemo(() => {
    const tex = catBase.clone()
    tex.flipY = false
    tex.colorSpace = SRGBColorSpace
    tex.needsUpdate = true
    const mat = materials.Cat.clone()
    mat.colorNode = texture(tex, uv())
    return mat
  }, [materials.Cat, catBase])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="rig001">
          <primitive object={nodes.c_pos} />
          <primitive object={nodes.c_arms_polel} />
          <primitive object={nodes.c_arms_poler} />
          <primitive object={nodes.c_foot_ikr} />
          <primitive object={nodes.c_leg_poler} />
          <primitive object={nodes.c_foot_ikl} />
          <primitive object={nodes.c_leg_polel} />
          <primitive object={nodes.c_hand_ikr} />
          <primitive object={nodes.c_hand_ikl} />
          <primitive object={nodes.root_refx} />
          <primitive object={nodes.lips_top_refx} />
          <primitive object={nodes.lips_bot_refx} />
          <primitive object={nodes.lips_roll_top_refx} />
          <primitive object={nodes.lips_roll_bot_refx} />
          <primitive object={nodes.jaw_refx} />
          <primitive object={nodes.teeth_bot_refx} />
          <primitive object={nodes.teeth_top_refx} />
          <primitive object={nodes.tong_01_refx} />
          <primitive object={nodes.chin_02_refx} />
          <primitive object={nodes.nose_01_refx} />
          <primitive object={nodes.eye_offset_refl} />
          <primitive object={nodes.c_eye_targetx} />
          <primitive object={nodes.eye_offset_refr} />
          <primitive object={nodes.eyebrow_full_refl} />
          <primitive object={nodes.eyebrow_full_refr} />
          <primitive object={nodes.cheek_smile_refl} />
          <primitive object={nodes.cheek_smile_refr} />
          <group name="Body001">
            <skinnedMesh name="Torus001" geometry={nodes.Torus001.geometry} material={catMat} skeleton={nodes.Torus001.skeleton} />
            <skinnedMesh name="Torus001_1" geometry={nodes.Torus001_1.geometry} material={materials.Gloves_Socks} skeleton={nodes.Torus001_1.skeleton} />
          </group>
          <group name="Eyes001">
            <skinnedMesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials.Eyes} skeleton={nodes.Mesh.skeleton} />
            <skinnedMesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.Pupils} skeleton={nodes.Mesh_1.skeleton} />
          </group>
          <skinnedMesh name="Gloves001" geometry={nodes.Gloves001.geometry} material={materials.Gloves_Socks} skeleton={nodes.Gloves001.skeleton} />
          <skinnedMesh name="Head001" geometry={nodes.Head001.geometry} material={catMat} skeleton={nodes.Head001.skeleton} />
          <skinnedMesh name="Shoes001" geometry={nodes.Shoes001.geometry} material={materials.Shoes} skeleton={nodes.Shoes001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Cat_MASTER_Selfie_2.glb')
