/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/cat.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cat.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plinth.geometry} material={nodes.Plinth.material} />
      <mesh geometry={nodes.CatSculpture.geometry} material={nodes.CatSculpture.material} />
    </group>
  )
}

useGLTF.preload('/cat.glb')
